computer_easy = [{"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The programming language 'Python' is based off a modified version of 'JavaScript'.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The logo for Snapchat is a Bell.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Ada Lovelace is often considered the first computer programmer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "'HTML' stands for Hypertext Markup Language.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "In most programming languages, the operator ++ is equivalent to the statement '+= 1'.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The Windows 7 operating system has five main editions.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The Windows ME operating system was released in the year 2000.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Linux was first created as an alternative to Windows XP.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The Python programming language gets its name from the British comedy group 'Monty Python'.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                  "question": "CPU stand for 'Central Processor Unit'", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                  "question": "GHz stand for 'Gigahertz'", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                  "question": "Nougat is the code name for the mobile operating system Android 7.0",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                  "question": "The computer software acronym JVM stand for 'Java Virtual Machine'",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]}]

computer_medium = [{"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "The HTML5 standard was published in 2014.", "correct_answer": "True",
                    "incorrect_answers": ["False"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "The common software-programming acronym 'I18N' comes from the term 'Interlocalization'.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "The first computer bug was formed by faulty wires.", "correct_answer": "False",
                    "incorrect_answers": ["True"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "FLAC stands for 'Free Lossless Audio Condenser'",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "The very first recorded computer 'bug' was a moth found inside a Harvard Mark II computer.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "'Windows NT' is a monolithic kernel.", "correct_answer": "False",
                    "incorrect_answers": ["True"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "MacOS is based on Linux.", "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "The open source program Redis is a relational database server.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "AMD created the first consumer 64-bit processor.", "correct_answer": "True",
                    "incorrect_answers": ["False"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "The first dual-core CPU was the Intel Pentium D.", "correct_answer": "False",
                    "incorrect_answers": ["True"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "It's not possible to format a write-protected DVD-R Hard Disk.",
                    "correct_answer": "True", "incorrect_answers": ["False"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "Android versions are named in alphabetical order.", "correct_answer": "True",
                    "incorrect_answers": ["False"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
                    "correct_answer": "False", "incorrect_answers": ["True"]},
                   {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                    "question": "A Boolean value of '0' represents True/False",
                    "correct_answer": "False", "incorrect_answers": ["True"]}]

computer_hard = [{"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                  "question": "DHCP stands for Dynamic Host Configuration Port.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                  "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                  "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "The Harvard architecture for micro-controllers added Instruction additional bus",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "HTTP run on port 443", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "Ageia is the original author of the realtime physics engine called PhysX",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "Stack is the data structure which applies FILO", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "Quantum Teleportation is the name of the process that sends one qubit of information using two bits of classical information",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "The International System of Quantities refer 1024 bytes as Kibibyte",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "IBM was the first company to use the term 'Golden Master'",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "Dutch computer scientist Mark Overmars is known for creating 'Game Maker' a game development engine.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "Pravetz 8D was the name of the first Bulgarian personal computer", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "The type of sound chip does the Super Nintendo Entertainment System (SNES) have, is ADPCM Sampler",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "ALU can be built using only NAND gates",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "Coffee Lake is the codename of the eighth generation Intel Core micro-architecture launched in October 2017",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "Cherry MX Blue is the Cherry MX mechanical keyboard switches which is both tactile and clicky.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
                  "question": "Secret sharing scheme is the algorithm for which Ron Rivest is not famous for creating.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]}]
computer_list = [computer_easy, computer_medium, computer_hard]