movie_easy = [{"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "Han Solo's co-pilot and best friend, 'Chewbacca' is an Ewok.",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "The movie 'The Nightmare before Christmas' was all done with physical objects.",
               "correct_answer": "True", "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "Leonardo DiCaprio won an Oscar for Best Actor in 2004 for 'The Aviator'.",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
               "correct_answer": "True", "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "The 2010 film 'The Social Network' is a biographical drama film about MySpace founder Tom Anderson.",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "The word 'Inception' came from the 2010 blockbuster hit 'Inception'.",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "In the original script of 'The Matrix', the machines used humans as additional computing power instead of batteries.",
               "correct_answer": "True", "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
               "correct_answer": "True", "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "Samuel L. Jackson had the words, 'Bad Motherf*cker' in-scripted on his lightsaber during the filming of Star Wars.",
               "correct_answer": "True", "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "In the movie The Revenant, DiCaprio's character hunts down the killer of his son.",
               "correct_answer": "True", "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "Brandon Routh plays the titular character in the movie 'John Wick'.",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "George Lucas directed the entire original Star Wars trilogy.", "correct_answer": "False",
               "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "'Minions' was released on the June 10th, 2015.", "correct_answer": "False",
               "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "Actor Tommy Chong served prison time.", "correct_answer": "True",
               "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "'Foodfight!' earned less than $80,000 at box office.", "correct_answer": "True",
               "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
               "question": "In Alfred Hitchcock's film 'Psycho', it is said he used chocolate syrup to "
                           "simulate the blood in the famous shower scene from ",
               "correct_answer": "True", "incorrect_answers": ["False"]}]

movie_medium = [{"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "There are not any live-action clones in 'Star Wars: Episode III - Revenge of the Sith'.",
                 "correct_answer": "True", "incorrect_answers": ["False"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "The color of the pills in the Matrix were Blue and Yellow.", "correct_answer": "False",
                 "incorrect_answers": ["True"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "The Xenomorph from the science fiction film 'Alien' has acidic blood.",
                 "correct_answer": "True", "incorrect_answers": ["False"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "Sean Connery wasn't in 'Indiana Jones and the Kingdom of the Crystal Skull', because he found retirement too enjoyable.",
                 "correct_answer": "True", "incorrect_answers": ["False"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "Joan Cusack starred in the 2009 disaster movie, '2012'.",
                 "correct_answer": "False", "incorrect_answers": ["True"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "The movie 'Tron' received an Oscar nomination for Best Visual Effects.",
                 "correct_answer": "False", "incorrect_answers": ["True"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "The original ending of 'Little Shop Of Horrors' has the plants taking over the world.",
                 "correct_answer": "True", "incorrect_answers": ["False"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "In the movie 'The Iron Giant', 'Hogarth Hughes' is the protagonist.",
                 "correct_answer": "True",
                 "incorrect_answers": ["False"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "Ben Stiller played the main character in the 1990 film 'Edward Scissorhands'.",
                 "correct_answer": "False",
                 "incorrect_answers": ["True"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "In the 2010 Nightmare on Elm Street reboot, Jackie Earle Haley played Freddy Kruger.",
                 "correct_answer": "True",
                 "incorrect_answers": ["False"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "In Back to the Future Part II, Marty and Dr. Emmett Brown go to future date 'October 21, 2015'.",
                 "correct_answer": "True",
                 "incorrect_answers": ["False"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "Darth Vader's famous reveal to Luke is iconic with 'Luke, I am your father!'",
                 "correct_answer": "False",
                 "incorrect_answers": ["True"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "Atraiyu is the correct spelling of the protagonist of the book in The NeverEnding Story (1984).",
                 "correct_answer": "False", "incorrect_answers": ["True"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "Leonardo Di Caprio won his first Best Actor Oscar for his performance in The Wolf Of Wall Street.",
                 "correct_answer": "False",
                 "incorrect_answers": ["False"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "Gilbert Gottfried voiced the talking parrot 'Iago'; in Disney's 1992 adaptation of Aladdin.",
                 "correct_answer": "True",
                 "incorrect_answers": ["False"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "Maurice Micklewhite is the birth name of Michael Caine.", "correct_answer": "True",
                 "incorrect_answers": ["False"]},
                {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                 "question": "The killer in the 1981 film 'My Bloody Valentine' wears Clown costume",
                 "correct_answer": "False",
                 "incorrect_answers": ["True"]}]

movie_hard = [{"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
               "question": "'Cube', 'Cube 2: Hypercube' and 'Cube Zero' were directed by "
                           "the same person.",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
               "question": "The weapon Clint Eastwood uses in 'Dirty Harry' was a .44 Automag.",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "'Vertigo' was the first of Alfred Hitchcock's movies to be filmed in colour.",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "'Duck Soup' was the last Marx Brothers film to feature Zeppo.", "correct_answer": "True",
               "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "In the film 'Interstellar', they spend 23 years, 4 months, and 8 days on Miller's planet",
               "correct_answer": "True",
               "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "In the 1976 film 'Taxi Driver, Travis bought 2 guns from the salesman",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "Alfred Hitchcock used Chocolate syrup as blood in the film 'Psycho'",
               "correct_answer": "True",
               "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "Distant Drums was the first movie to ever use a Wilhelm Scream", "correct_answer": "True",
               "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "In the movie 'Scream' Dewey Rile is Ghost Face.",
               "correct_answer": "False",
               "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "Thinking Machines CM-5 is the name of the supercomputer located in the control room in 'Jurassic Park' (1993)",
               "correct_answer": "True",
               "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "In the 'Jurassic Park' universe, 'Jurassic Park: San Diego' begun construction in 1985.",
               "correct_answer": "True", "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "Sergio Leone, Ennio Morricone, and Tonino Delli Colli, made up the trio in 'The Good, the Bad, and the Ugly' ",
               "correct_answer": "False",
               "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "Sigourney Weaver portrayed Dr. Grace Augustine in the James Cameron movie 'Avatar'",
               "correct_answer": "True",
               "incorrect_answers": ["False"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "'The Day The Earth Stood Still' sci-fi cult films plot concerns aliens attempting to prevent humans from creating a doomsday weapon.",
               "correct_answer": "False",
               "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "In the film 'Harry Potter and the Order of The Phoenix', Harry Potter's scream, after Sirius Black died, was muted because of Too Loud",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Film", "type": "multiple", "difficulty": "hard",
               "question": "Shambala was the wifi password given to Stephen Strange in Doctor Strange",
               "correct_answer": "True", "incorrect_answers": ["False"]}]

movie_list = [movie_easy, movie_medium, movie_hard]



