gk_easy = [{"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "The Great Wall of China is visible from the moon.", "correct_answer": "False",
            "incorrect_answers": ["True"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "Gumbo is a stew that originated in Louisiana.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "Nutella is produced by the German company Ferrero.", "correct_answer": "False",
            "incorrect_answers": ["True"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "'Ananas' is mostly used as the word for Pineapple in other languages.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "The Sun rises from the North.", "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "The color orange is named after the fruit.", "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "You can legally drink alcohol while driving in Mississippi.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Pluto is a planet.",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "The Lego Group was founded in 1932.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "One of Donald Trump's 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "'27 Club' is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "A pasodoble is a type of Italian pasta sauce.", "correct_answer": "False",
            "incorrect_answers": ["True"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "Slovakia is a member of European Union-",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
            "question": "The mitochondria is the powerhouse of the cell.", "correct_answer": "True",
            "incorrect_answers": ["False"]}]

gk_medium = [{"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "'Typewriter' is the longest word that can be typed using only the first row on a QWERTY keyboard.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "Coca-Cola's original colour was green.", "correct_answer": "False",
              "incorrect_answers": ["True"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "The vapor produced by e-cigarettes is actually water.", "correct_answer": "False",
              "incorrect_answers": ["True"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "The sum of all the numbers on a roulette wheel is 666.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "Furby was released in 1998.", "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "There are 86400 seconds in a day.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "The average woman is 5 inches \/ 13 centimeters shorter than the average man.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "The term 'Spam' came before the food product 'Spam'.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "Kissing someone for one minute burns about 2 calories.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "The French word to travel is 'Travail'", "correct_answer": "False",
              "incorrect_answers": ["True"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "The French word for 'glass' is 'glace'.", "correct_answer": "False",
              "incorrect_answers": ["True"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "Albert Einstein had trouble with mathematics when he was in school.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "The scientific name for the Southern Lights is Aurora Australis.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "Haggis is traditionally ate on Burns Night.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the snack on the streets of Chicago.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "The commercial UK channel ITV stands for 'International Television'.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "'Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.'; is a grammatically correct sentence.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
              "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
              "correct_answer": "True", "incorrect_answers": ["False"]}]

gk_hard = [{"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
            "question": "This is the correct spelling of 'Supercalifragilisticexpialidocious'.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
            "question": "'Number 16 Bus Shelter' was a child's name that was approved by the New Zealand government.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
            "question": "In Scandinavian languages, the letter &Aring; means river.", "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
            "question": "Stagecoach owned 'South West Trains' before losing the rights to FirstGroup and MTR in March of 2017.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
            "question": "Spoon theory is a theory, utilizing 'Spoons' as a metaphor for energy they can use in a day.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
            "question": "NCIS stands for 'Navy Corps Investigative Service'", "correct_answer": "False",
            "incorrect_answers": ["True"]},
           {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
            "question": "Electronic music producer Kygo's popularity skyrocketed after a certain remix. He remixed 'Ed Sheeran - I See Fire'.'",
            "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
            "question": "20 MPH is the airspeed velocity of an unladen swallow.", "correct_answer": "False",
            "incorrect_answers": ["True"]},
           {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
            "question": "The words 'bungalow' and 'shampoo' originate from the languages of India.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
            "question": "Sciophobia is the fear of Shadows.", "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
            "question": "The Simoleon Family is an existing family in 'The Sims'.",
            "correct_answer": "False",
            "incorrect_answers": ["True"]},
           {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
            "question": "In flight systems, the initialism 'TCAS' stand for Traffic Configuration Alignment System. ",
            "correct_answer": "False",
            "incorrect_answers": ["True"]},
           {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
            "question": "Chartreuse is a color between yellow and Green.", "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
            "question": "88 notes are there on a standard grand piano.", "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
            "question": "Time is the most commonly used noun in the English language.", "correct_answer": "TRue",
            "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
            "question": "The word 'astasia' means The inability to stand up.",
            "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
            "question": "'San Fransisco, CA' does NOT have a United States Minting location.",
            "correct_answer": "False",
            "incorrect_answers": ["True"]}]
gk_list = [gk_easy, gk_medium, gk_hard]
