vg_easy = [{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "The main character in the 'Half-Life' franchise is named Morgan Freeman.",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "The song 'Megalovania' by Toby Fox made its third appearence in the 2015 RPG 'Undertale'.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "'Half-Life 2' runs on the Source Engine.", "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.", "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "Minecraft can be played with a virtual reality headset.", "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "In the 'Half-Life' series, 'H.E.V' stands for 'Hazardous Evasiveness Vest'",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.", "correct_answer": "False",
            "incorrect_answers": ["True"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "Valve's 'Portal' and 'Half-Life' franchises exist within the same in-game universe.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "The ghosts in 'Pac-Man' and 'Ms. Pac-Man' have completely different behavior.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "The game 'Pocket Morty' has a Morty called 'Pocket Mortys Morty'.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "Activision created Battlefield 1.", "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "In the 'S.T.A.L.K.E.R.' series, the Freedom faction wishes to destroy the supernatural area known as  'the Zone'.",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "Codemasters is the developer of the Gran Turismo series.", "correct_answer": "False",
            "incorrect_answers": ["True"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "There are 2 player roles in Trouble in Terrorist Town.", "correct_answer": "False",
            "incorrect_answers": ["True"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
            "question": "Doki Doki Literature Club was developed in Japan.", "correct_answer": "False",
            "incorrect_answers": ["True"]}]


vg_medium = [{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "Nintendo started out as a playing card manufacturer.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "DragonForce's Through the Fire and Flames, is widely considered to be the hardest song in the Guitar Hero series.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "The Ace Attorney trilogy was supposed to end with 'Phoenix Wright: Ace Attorney-Trials and Tribulations' as its final game.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "The Sniper's SMG in Team Fortress 2, was originally intended to be the Scout's primary weapon.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "In the game 'Subnautica', a 'Cave Crawler' will attack you.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "Pistons were added to Minecraft in Beta 1.5.", "correct_answer": "False",
              "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "David Baszucki was a co-founder of ROBLOX Corporation.", "correct_answer": "True",
              "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "In the video game 'Transistor', 'Red' is the name of the main character.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "Resident Evil 4 was originally meant to be a Nintendo GameCube exclusive.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "In 'Super Mario World', the rhino mini-boss, Reznor, is named after the lead singer of the band 'Nine Inch Nails'.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "In 'Call Of Duty: Zombies', you can upgrade the 'Apothicon Servant' in the 'Shadows Of Evil' map.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "The Fiat Multipla is a drivable car in 'Forza Horizon 3'.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "In 'League of Legends', there exists four different types of Dragon.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "The character that would eventually become Dr. Eggman was considered for the role of Sega's new flagship mascot before Sonic was.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "In the game 'Until Dawn' Emily is the only playable character who can be killed by another playable character directly.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
              "question": "Minecraft wasn't the original name to Minecraft.", "correct_answer": "True",
              "incorrect_answers": ["False"]}]

vg_hard = [{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "The retail disc of Tony Hawk's Pro Skater 5 only comes with the tutorial.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "In 'The Sims' series, the most members in a household you can have is 8.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "Unturned originally started as a Roblox game.", "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "In the game 'Melty Blood Actress Again Current Code', you can enter Blood Heat mode in Half Moon style.",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "The first 'Metal Gear' game was released for the PlayStation 1.",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "In 'Portal 2', Cave Johnson started out Aperture Science as a shower curtain company.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "In Undertale, having a 'Fun Value' set to 56-57 will play the 'Wrong Number Song Call'.",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "TF2: Sentry rocket damage falloff is calculated based on the distance between the sentry and the enemy, not the engineer and the enemy",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "The names of Roxas's Keyblades in Kingdom Hearts are 'Oathkeeper' and 'Oblivion'.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "All of these maps were in 'Tom Clancy's Rainbow Six Siege' on its initial release: House, Clubhouse, Border, Consulate.",
            "correct_answer": "False", "incorrect_answers": ["True"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "The video game 'Fuel' has an open world that is 5,560 square miles.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "In 'Minecraft', gold tools are faster than diamond tools.", "correct_answer": "True",
            "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "The Paradox Interactive game 'Stellaris' was released in 2016.",
            "correct_answer": "True", "incorrect_answers": ["False"]},
           {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
            "question": "In The Witcher 3, the Zoltan Chivay Gwent card can be found under the Hanged Man's Tree.",
            "correct_answer": "True", "incorrect_answers": ["False"]}]
vg_list = [vg_easy, vg_medium, vg_hard]